/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlEstudiantes;
import javax.swing.JOptionPane;
import modelo.Registro;

/**
 *
 * @author kevin
 */
public class GUIEstudiantes extends javax.swing.JDialog {

    private ControlEstudiantes controlEstudiantes;
    
    
    /**
     * Creates new form GUIEstudiantes
     */
    public GUIEstudiantes(java.awt.Frame parent, boolean modal, Registro registro, PanelTablaEstudiantes panelTablaEstudiantes){
        super(parent,modal);
        initComponents();
        controlEstudiantes = new ControlEstudiantes(this, panelDataEstudiante1, panelBotonesEstudiante1, registro, panelTablaEstudiantes);
        panelBotonesEstudiante1.addEscucha(controlEstudiantes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataEstudiante1 = new vista.PanelDataEstudiante();
        panelBotonesEstudiante1 = new vista.PanelBotonesEstudiante();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración estudiantes");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("DejaVu Sans Mono", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonesEstudiante1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .addComponent(panelDataEstudiante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDataEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotonesEstudiante panelBotonesEstudiante1;
    private vista.PanelDataEstudiante panelDataEstudiante1;
    // End of variables declaration//GEN-END:variables

    public static void mensage(String mensage){
        JOptionPane.showMessageDialog(null, mensage);
    }
    
   
    public static int mensajeConfirmar(String data) {
        return  JOptionPane.showConfirmDialog(null, data);
    }
    
    public PanelBotonesEstudiante getPanelBotones(){
        return panelBotonesEstudiante1;
    }
    public PanelDataEstudiante getPanelData(){
        return panelDataEstudiante1; 
    }
}
